const list = [{
  id: 'a',
  head: 'A',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'b',
  head: 'B',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'c',
  head: 'C',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'd',
  head: 'D',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'e',
  head: 'E',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'f',
  head: 'F',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'g',
  head: 'G',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'h',
  head: 'H',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'i',
  head: 'I',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'j',
  head: 'J',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'k',
  head: 'K',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'l',
  head: 'L',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'm',
  head: 'M',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'n',
  head: 'N',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'o',
  head: 'O',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'p',
  head: 'P',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'q',
  head: 'Q',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'r',
  head: 'R',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 's',
  head: 'S',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 't',
  head: 'T',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'u',
  head: 'U',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'v',
  head: 'V',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'w',
  head: 'W',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'x',
  head: 'X',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'y',
  head: 'Y',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, {
  id: 'z',
  head: 'Z',
  children: [{
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }, {
    text: '数据',
    imgUrl: '/images/logo.jpg'
  }]
}, ]

export default list